language: ruby
rvm:
- 2.2.4
deploy:
  provider: heroku
  api_key:
    secure: RQY6gL9CPYQK6B9lO0xdirWJwfr2+JzxQCJQODrehNYcRh3XSzPVHp/PnWj8UxdWnxleCJVnuFAU7corTDogiXjj74tj3AAsNJ+HYpbK4wZmAdWpvKvo1gAMeAl+IwmOdsFBtn/CLRd4HzFQW6hDT0Ss8pcqcWCgAbv0C85bt0qSxMN+UagOEiOA8Zkr+7TCZSIFEYu8mOwmhpHDUvzYKQgsvLnE80jkuQt3gfc+fx5azX6pu8tRZBOxhtNNsIUD7Mrp6cERq4oGNPO3l+vemrvgrFAoIxBt1XpQrlZAJhnbx+bPgXp9S81l0ry+ttFG3Vl5NEm/hQPIYiiJuIkBWxRchgarvaFShju6wv+adUiZjJQBSkzolVOnP2jmIoa0nHnU2mfjIl9C+fnY8AVmi1TDDO2yjKpVtz0Jextw/zQtgJxifrsQoJ3rrlah6T8AHjwwt4ArlnrXNfjxZZIfSTH5i0C8STCtYLC55xCPh5TcXE7c9BDzSyQWU1ziU1iqu7A96ugOkbhkQJjFMs5tOV4Za91flfdl9WWCqcjkHNdtcbhfUAwQppXJgaqTSjDMwTAQwU3/eKHeS7EaN0w6YMkgIZjpsVxiTb4GsVw6ha3+7fWWiTCBh62OmB+bGbT3e91rx/BOKnhw/yg2nVXuhQtMQC8+dVLWnh4S8RT+xaQ=
  app: limitless-hamlet-44082
  on:
    repo: Globuss/projet
